# Generated by Django 3.2 on 2022-03-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='types_of_room',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], default='Single', max_length=15),
        ),
    ]
