# Generated by Django 3.2 on 2022-03-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_bookings_types_of_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='number_of_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='types_of_room',
            field=models.CharField(choices=[('Sgl', 'Single Room'), ('Dbl', 'Double Room'), ('Fam', 'Family Room')], default='Single', max_length=15),
        ),
    ]
