# Generated by Django 3.2 on 2022-03-24 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_auto_20220324_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='check_in_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bookings',
            name='number_of_nights',
            field=models.IntegerField(default=1),
        ),
    ]
