# Generated by Django 3.2 on 2022-04-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0006_auto_20220407_1859'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='bookingsystem_booking_number_of_guests__range',
        ),
    ]
